apiVersion: v1
kind: Secret
metadata:
  name: {{ include "data-sync.fullname" . }}-secret
  labels:
    {{- include "data-sync.labels" . | nindent 4 }}
type: Opaque
stringData:
  REDIS_PASSWORD: {{ .Values.secrets.redisPassword | quote }}