variable "aws_region" {
  type        = string
  default     = "ap-south-1"
  description = "AWS Region for deployment"
}

variable "hub_vpc_cidr" {
  type        = string
  default     = "10.0.0.0/16"
  description = "CIDR block for Hub VPC"
}

variable "hub_cluster_name" {
  type        = string
  default     = "hub-eks-cluster"
  description = "Name of the Hub EKS Cluster"
}

variable "argocd_chart_version" {
  type        = string
  default     = "10.4.2" # Standard argo-helm release version
  description = "Version of the argo-cd Helm chart"
}

# variable "github_app_id" {
#   type        = string
#   description = "The App ID of your GitHub App"
#   sensitive   = true
# }

# variable "github_app_installation_id" {
#   type        = string
#   description = "The Installation ID for your GitHub App target organization/account"
#   sensitive   = true
# }

# variable "github_app_private_key" {
#   type        = string
#   description = "The Private Key (PEM format) generated by the GitHub App"
#   sensitive   = true
# }

# variable "github_org_url" {
#   type        = string
#   default     = "https://github.com/test-repo-app"
#   description = "Base HTTPS URL for your GitHub organization"
# }