replicaCount: 2

image:
  repository: 986293906729.dkr.ecr.ap-south-1.amazonaws.com/data-sync
  pullPolicy: IfNotPresent
  tag: "v1.0.0"

config:
  appEnv: "staging"
  redisHost: "redis-master.data-sync-staging.svc.cluster.local"
  redisPort: "6379"
  logLevel: "INFO"
  workers: "2"
  maxConnections: "50"

secrets:
  redisPassword: "staging-secret-redis-password"

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: false