apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-ingressgateway
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://istio-release.storage.googleapis.com/charts
      chart: gateway
      targetRevision: 1.30.5
      helm:
        valueFiles:
          - $values/platform/istio/values/ingressgateway.yaml
    - repoURL: https://github.com/parthcs-secondary/terraform-base-eks-module.git
      targetRevision: zaidyn
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-ingress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
